package au.edu.unsw.soacourse.autocheck;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-10-21T11:35:20.949+11:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://autocheck.soacourse.unsw.edu.au", name = "AutoCheckServicePortType")
@XmlSeeAlso({au.edu.unsw.soacourse.pdv.ObjectFactory.class, au.edu.unsw.soacourse.crv.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AutoCheckServicePortType {

    @WebResult(name = "AutoCheckResponse", targetNamespace = "http://autocheck.soacourse.unsw.edu.au", partName = "payload")
    @Action(input = "http://autocheck.soacourse.unsw.edu.au/autoCheckProcess", output = "http://autocheck.soacourse.unsw.edu.au/AutoCheck/autoCheckProcessResponse")
    @WebMethod(action = "http://autocheck.soacourse.unsw.edu.au/autoCheckProcess")
    public AutoCheckResponse autoCheckProcess(
        @WebParam(partName = "payload", name = "AutoCheckRequest", targetNamespace = "http://autocheck.soacourse.unsw.edu.au")
        AutoCheckRequest payload
    );
}
