package au.edu.unsw.soacourse.pdv;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-10-21T11:33:46.585+11:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "PDVService", 
                  wsdlLocation = "file:/Users/Solki/Documents/workspace/PDVService/src/main/resources/wsdl/PDV.wsdl",
                  targetNamespace = "http://pdv.soacourse.unsw.edu.au") 
public class PDVService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://pdv.soacourse.unsw.edu.au", "PDVService");
    public final static QName PDVService = new QName("http://pdv.soacourse.unsw.edu.au", "PDVService");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/Solki/Documents/workspace/PDVService/src/main/resources/wsdl/PDV.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PDVService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/Solki/Documents/workspace/PDVService/src/main/resources/wsdl/PDV.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PDVService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PDVService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PDVService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PDVService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PDVService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PDVService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns PDVService
     */
    @WebEndpoint(name = "PDVService")
    public PDVService getPDVService() {
        return super.getPort(PDVService, PDVService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PDVService
     */
    @WebEndpoint(name = "PDVService")
    public PDVService getPDVService(WebServiceFeature... features) {
        return super.getPort(PDVService, PDVService.class, features);
    }

}
