package au.edu.unsw.soacourse.crv;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-10-21T11:34:00.358+11:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "CRVService", 
                  wsdlLocation = "file:/Users/Solki/Documents/workspace/CRVService/src/main/resources/wsdl/CRV.wsdl",
                  targetNamespace = "http://crv.soacourse.unsw.edu.au") 
public class CRVService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://crv.soacourse.unsw.edu.au", "CRVService");
    public final static QName CRVService = new QName("http://crv.soacourse.unsw.edu.au", "CRVService");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/Solki/Documents/workspace/CRVService/src/main/resources/wsdl/CRV.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CRVService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/Solki/Documents/workspace/CRVService/src/main/resources/wsdl/CRV.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CRVService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CRVService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CRVService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CRVService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CRVService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CRVService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns CRVService
     */
    @WebEndpoint(name = "CRVService")
    public CRVService getCRVService() {
        return super.getPort(CRVService, CRVService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CRVService
     */
    @WebEndpoint(name = "CRVService")
    public CRVService getCRVService(WebServiceFeature... features) {
        return super.getPort(CRVService, CRVService.class, features);
    }

}
